---
plugin: amazon.aws.aws_ec2
regions:
  - "{{ (lookup('file', lookup('env', 'PWD') + '/terraform/global.auto.tfvars.json') | from_json).aws_region }}"
filters:
  instance-id: "{{ lookup('pipe', 'terraform -chdir=' + lookup('env', 'PWD') + '/terraform output -raw instance_id') | trim }}"
hostnames:
  - ip-address
hostvars_prefix: aws_
compose:
  ec2_tags: aws_ec2_tags
  ansible_user: "'ec2-user'"
  ansible_private_key_file: "'~/.ssh/outline-ec2'"
  ansible_host: aws_ipv6_address | default(aws_public_ip_address)
